[2022-01-02 15:23:55,986] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: rank_update.make_indicator 2022-01-01T15:23:52.146192+00:00 [queued]>
[2022-01-02 15:23:55,992] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: rank_update.make_indicator 2022-01-01T15:23:52.146192+00:00 [queued]>
[2022-01-02 15:23:55,992] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2022-01-02 15:23:55,992] {taskinstance.py:1068} INFO - Starting attempt 1 of 1
[2022-01-02 15:23:55,992] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2022-01-02 15:23:55,999] {taskinstance.py:1087} INFO - Executing <Task(BashOperator): make_indicator> on 2022-01-01T15:23:52.146192+00:00
[2022-01-02 15:23:56,000] {standard_task_runner.py:52} INFO - Started process 1123252 to run task
[2022-01-02 15:23:56,005] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'rank_update', 'make_indicator', '2022-01-01T15:23:52.146192+00:00', '--job-id', '1898', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/rank_update.py', '--cfg-path', '/tmp/tmpdegzchud', '--error-file', '/tmp/tmp1bx5kpkh']
[2022-01-02 15:23:56,005] {standard_task_runner.py:77} INFO - Job 1898: Subtask make_indicator
[2022-01-02 15:23:56,038] {logging_mixin.py:104} INFO - Running <TaskInstance: rank_update.make_indicator 2022-01-01T15:23:52.146192+00:00 [running]> on host airflowvm
[2022-01-02 15:23:56,112] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=rank_update
AIRFLOW_CTX_TASK_ID=make_indicator
AIRFLOW_CTX_EXECUTION_DATE=2022-01-01T15:23:52.146192+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-01-01T15:23:52.146192+00:00
[2022-01-02 15:23:56,112] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2022-01-02 15:23:56,112] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'python3 /home/airflow/parser4Study/multiple_parser.py /home/airflow/AlgorithmStudy_211124/220104/']
[2022-01-02 15:23:56,115] {subprocess.py:75} INFO - Output:
[2022-01-02 15:23:56,504] {subprocess.py:79} INFO - Traceback (most recent call last):
[2022-01-02 15:23:56,504] {subprocess.py:79} INFO -   File "/home/airflow/parser4Study/multiple_parser.py", line 68, in <module>
[2022-01-02 15:23:56,504] {subprocess.py:79} INFO -     multiple_parser.load_and_parse_files()
[2022-01-02 15:23:56,504] {subprocess.py:79} INFO -   File "/home/airflow/parser4Study/multiple_parser.py", line 17, in load_and_parse_files
[2022-01-02 15:23:56,504] {subprocess.py:79} INFO -     for filename in os.listdir(self.route):
[2022-01-02 15:23:56,504] {subprocess.py:79} INFO - FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/AlgorithmStudy_211124/220104/'
[2022-01-02 15:23:56,542] {subprocess.py:83} INFO - Command exited with return code 1
[2022-01-02 15:23:56,547] {taskinstance.py:1481} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/sandbox/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1137, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/sandbox/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/sandbox/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/sandbox/lib/python3.8/site-packages/airflow/operators/bash.py", line 180, in execute
    raise AirflowException('Bash command failed. The command returned a non-zero exit code.')
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code.
[2022-01-02 15:23:56,548] {taskinstance.py:1524} INFO - Marking task as FAILED. dag_id=rank_update, task_id=make_indicator, execution_date=20220101T152352, start_date=20220102T152355, end_date=20220102T152356
[2022-01-02 15:23:56,579] {local_task_job.py:151} INFO - Task exited with return code 1
