[2021-12-20 05:41:36,258] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available 2021-12-19T00:00:00+00:00 [queued]>
[2021-12-20 05:41:36,265] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available 2021-12-19T00:00:00+00:00 [queued]>
[2021-12-20 05:41:36,265] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-12-20 05:41:36,265] {taskinstance.py:1068} INFO - Starting attempt 1 of 1
[2021-12-20 05:41:36,266] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-12-20 05:41:36,280] {taskinstance.py:1087} INFO - Executing <Task(HttpSensor): is_api_available> on 2021-12-19T00:00:00+00:00
[2021-12-20 05:41:36,283] {standard_task_runner.py:52} INFO - Started process 35804 to run task
[2021-12-20 05:41:36,288] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'user_processing', 'is_api_available', '2021-12-19T00:00:00+00:00', '--job-id', '235', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpirffs_q9', '--error-file', '/tmp/tmpm1lpbcdv']
[2021-12-20 05:41:36,289] {standard_task_runner.py:77} INFO - Job 235: Subtask is_api_available
[2021-12-20 05:41:36,330] {logging_mixin.py:104} INFO - Running <TaskInstance: user_processing.is_api_available 2021-12-19T00:00:00+00:00 [running]> on host airflowvm
[2021-12-20 05:41:36,400] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2021-12-19T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-12-19T00:00:00+00:00
[2021-12-20 05:41:36,400] {http.py:101} INFO - Poking: api/
[2021-12-20 05:41:36,416] {base.py:69} INFO - Using connection to: id: user_api. Host: https://randomuser.me, Port: None, Schema: , Login: , Password: ***, extra: {}
[2021-12-20 05:41:36,418] {http.py:140} INFO - Sending 'GET' to url: https://randomuser.me/api/
[2021-12-20 05:41:36,775] {base.py:243} INFO - Success criteria met. Exiting.
[2021-12-20 05:41:36,788] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=is_api_available, execution_date=20211219T000000, start_date=20211220T054136, end_date=20211220T054136
[2021-12-20 05:41:36,848] {taskinstance.py:1245} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-12-20 05:41:36,867] {local_task_job.py:151} INFO - Task exited with return code 0
